// ============================================================
// DCI Programming Labs — Lab Catalog
// Generated by scripts/generate-dci-programming-content.mjs
// ============================================================

import { inputValidationBasicsLab } from "./labs/input-validation-basics";
import { canonicalizationNormalizationLab } from "./labs/canonicalization-normalization";
import { outputEncodingTemplatesLab } from "./labs/output-encoding-templates";
import { safeDomUpdatesLab } from "./labs/safe-dom-updates";
import { authenticationBasicsLab } from "./labs/authentication-basics";
import { registrationRateLimitsLab } from "./labs/registration-rate-limits";
import { sessionIdGenerationLab } from "./labs/session-id-generation";
import { sessionFixationDefenseLab } from "./labs/session-fixation-defense";
import { secureErrorHandlingLab } from "./labs/secure-error-handling";
import { secureLoggingBasicsLab } from "./labs/secure-logging-basics";
import { dependencyBoundaryChecksLab } from "./labs/dependency-boundary-checks";
import { leastPrivilegeDefaultsLab } from "./labs/least-privilege-defaults";
import { owaspTop10MappingLab } from "./labs/owasp-top10-mapping";
import { insecureDeserializationBasicsLab } from "./labs/insecure-deserialization-basics";
import { pathTraversalDefenseLab } from "./labs/path-traversal-defense";
import { commandInjectionGuardrailsLab } from "./labs/command-injection-guardrails";
import { secretsInCodeReviewLab } from "./labs/secrets-in-code-review";
import { memorySafeStringHandlingLab } from "./labs/memory-safe-string-handling";
import { secureFeatureRolloutsLab } from "./labs/secure-feature-rollouts";
import { threatModelingForDevsLab } from "./labs/threat-modeling-for-devs";
import { reflectedXssPreventionLab } from "./labs/reflected-xss-prevention";
import { storedXssCommentModerationLab } from "./labs/stored-xss-comment-moderation";
import { domXssClientRenderingLab } from "./labs/dom-xss-client-rendering";
import { csrfTokenRotationLab } from "./labs/csrf-token-rotation";
import { sameSiteCookiePoliciesLab } from "./labs/same-site-cookie-policies";
import { sqlParameterizedQueriesLab } from "./labs/sql-parameterized-queries";
import { ormQueryBuilderSafetyLab } from "./labs/orm-query-builder-safety";
import { contentSecurityPolicyBasicsLab } from "./labs/content-security-policy-basics";
import { clickjackingFrameAncestorsLab } from "./labs/clickjacking-frame-ancestors";
import { secureCookieHardeningLab } from "./labs/secure-cookie-hardening";
import { fileUploadValidationLab } from "./labs/file-upload-validation";
import { templateInjectionDefenseLab } from "./labs/template-injection-defense";
import { openRedirectControlsLab } from "./labs/open-redirect-controls";
import { ssrfGuardrailsLab } from "./labs/ssrf-guardrails";
import { corsOriginReviewLab } from "./labs/cors-origin-review";
import { websocketSessionSecurityLab } from "./labs/websocket-session-security";
import { cachePoisoningDefenseLab } from "./labs/cache-poisoning-defense";
import { thirdPartyScriptGovernanceLab } from "./labs/third-party-script-governance";
import { browserStorageHygieneLab } from "./labs/browser-storage-hygiene";
import { webErrorObservabilityLab } from "./labs/web-error-observability";
import { authBypassPullRequestsLab } from "./labs/auth-bypass-pull-requests";
import { insecureRandomnessReviewLab } from "./labs/insecure-randomness-review";
import { taintFlowReviewLab } from "./labs/taint-flow-review";
import { regexDosReviewLab } from "./labs/regex-dos-review";
import { staticAnalysisBasicsLab } from "./labs/static-analysis-basics";
import { dependencyScanTriageLab } from "./labs/dependency-scan-triage";
import { codeSmellRiskRankingLab } from "./labs/code-smell-risk-ranking";
import { unsafeCryptoReviewLab } from "./labs/unsafe-crypto-review";
import { accessControlDiffAnalysisLab } from "./labs/access-control-diff-analysis";
import { loggingGapReviewLab } from "./labs/logging-gap-review";
import { secretsDetectionPrsLab } from "./labs/secrets-detection-prs";
import { reviewCommentsSecurityLab } from "./labs/review-comments-security";
import { secureRefactorTriageLab } from "./labs/secure-refactor-triage";
import { architectureHotspotsAnalysisLab } from "./labs/architecture-hotspots-analysis";
import { sastRuleTuningReviewLab } from "./labs/sast-rule-tuning-review";
import { ciPipelineLeastPrivilegeLab } from "./labs/ci-pipeline-least-privilege";
import { buildAgentSecretsManagementLab } from "./labs/build-agent-secrets-management";
import { sbomGenerationReviewLab } from "./labs/sbom-generation-review";
import { containerBaseImageHardeningLab } from "./labs/container-base-image-hardening";
import { dockerfileSecurityChecksLab } from "./labs/dockerfile-security-checks";
import { kubernetesManifestSecurityLab } from "./labs/kubernetes-manifest-security";
import { iacScanningLab } from "./labs/iac-scanning";
import { policyAsCodeGuardrailsLab } from "./labs/policy-as-code-guardrails";
import { shiftLeftSecurityTestsLab } from "./labs/shift-left-security-tests";
import { artifactSigningVerificationLab } from "./labs/artifact-signing-verification";
import { ephemeralEnvironmentSecurityLab } from "./labs/ephemeral-environment-security";
import { dependencyCacheHardeningLab } from "./labs/dependency-cache-hardening";
import { releaseApprovalControlsLab } from "./labs/release-approval-controls";
import { cloudWorkloadIdentityLab } from "./labs/cloud-workload-identity";
import { incidentReadyPipelinesLab } from "./labs/incident-ready-pipelines";
import { apiAuthenticationPatternsLab } from "./labs/api-authentication-patterns";
import { authorizationCheckOrderLab } from "./labs/authorization-check-order";
import { rateLimitingStrategiesLab } from "./labs/rate-limiting-strategies";
import { jsonInputSanitizationLab } from "./labs/json-input-sanitization";
import { jwtValidationBasicsLab } from "./labs/jwt-validation-basics";
import { refreshTokenRotationLab } from "./labs/refresh-token-rotation";
import { oauthRedirectValidationLab } from "./labs/oauth-redirect-validation";
import { serviceToServiceAuthLab } from "./labs/service-to-service-auth";
import { graphqlResolverAuthorizationLab } from "./labs/graphql-resolver-authorization";
import { webhookSignatureVerificationLab } from "./labs/webhook-signature-verification";
import { idempotencyReplayDefenseLab } from "./labs/idempotency-replay-defense";
import { jobQueueHardeningLab } from "./labs/job-queue-hardening";
import { multiTenantDataIsolationLab } from "./labs/multi-tenant-data-isolation";
import { apiVersioningSecurityLab } from "./labs/api-versioning-security";
import { backendAbuseObservabilityLab } from "./labs/backend-abuse-observability";
import { secureStorageBasicsLab } from "./labs/secure-storage-basics";
import { certificatePinningDecisionsLab } from "./labs/certificate-pinning-decisions";
import { mobileAuthTokenHandlingLab } from "./labs/mobile-auth-token-handling";
import { reverseEngineeringRiskReviewLab } from "./labs/reverse-engineering-risk-review";
import { obfuscationSymbolStrippingLab } from "./labs/obfuscation-symbol-stripping";
import { secureMobileNetworkingLab } from "./labs/secure-mobile-networking";
import { localDataEncryptionLab } from "./labs/local-data-encryption";
import { mobileLoggingRedactionLab } from "./labs/mobile-logging-redaction";
import { clipboardScreenshotHygieneLab } from "./labs/clipboard-screenshot-hygiene";
import { deepLinkValidationLab } from "./labs/deep-link-validation";
import { rootedDeviceDetectionLab } from "./labs/rooted-device-detection";
import { clientSideSecretAvoidanceLab } from "./labs/client-side-secret-avoidance";
import { biometricFallbackSecurityLab } from "./labs/biometric-fallback-security";
import { thirdPartySdkReviewLab } from "./labs/third-party-sdk-review";
import { mobileDataLeakagePreventionLab } from "./labs/mobile-data-leakage-prevention";

export const labCatalog = [
  inputValidationBasicsLab,
  canonicalizationNormalizationLab,
  outputEncodingTemplatesLab,
  safeDomUpdatesLab,
  authenticationBasicsLab,
  registrationRateLimitsLab,
  sessionIdGenerationLab,
  sessionFixationDefenseLab,
  secureErrorHandlingLab,
  secureLoggingBasicsLab,
  dependencyBoundaryChecksLab,
  leastPrivilegeDefaultsLab,
  owaspTop10MappingLab,
  insecureDeserializationBasicsLab,
  pathTraversalDefenseLab,
  commandInjectionGuardrailsLab,
  secretsInCodeReviewLab,
  memorySafeStringHandlingLab,
  secureFeatureRolloutsLab,
  threatModelingForDevsLab,
  reflectedXssPreventionLab,
  storedXssCommentModerationLab,
  domXssClientRenderingLab,
  csrfTokenRotationLab,
  sameSiteCookiePoliciesLab,
  sqlParameterizedQueriesLab,
  ormQueryBuilderSafetyLab,
  contentSecurityPolicyBasicsLab,
  clickjackingFrameAncestorsLab,
  secureCookieHardeningLab,
  fileUploadValidationLab,
  templateInjectionDefenseLab,
  openRedirectControlsLab,
  ssrfGuardrailsLab,
  corsOriginReviewLab,
  websocketSessionSecurityLab,
  cachePoisoningDefenseLab,
  thirdPartyScriptGovernanceLab,
  browserStorageHygieneLab,
  webErrorObservabilityLab,
  authBypassPullRequestsLab,
  insecureRandomnessReviewLab,
  taintFlowReviewLab,
  regexDosReviewLab,
  staticAnalysisBasicsLab,
  dependencyScanTriageLab,
  codeSmellRiskRankingLab,
  unsafeCryptoReviewLab,
  accessControlDiffAnalysisLab,
  loggingGapReviewLab,
  secretsDetectionPrsLab,
  reviewCommentsSecurityLab,
  secureRefactorTriageLab,
  architectureHotspotsAnalysisLab,
  sastRuleTuningReviewLab,
  ciPipelineLeastPrivilegeLab,
  buildAgentSecretsManagementLab,
  sbomGenerationReviewLab,
  containerBaseImageHardeningLab,
  dockerfileSecurityChecksLab,
  kubernetesManifestSecurityLab,
  iacScanningLab,
  policyAsCodeGuardrailsLab,
  shiftLeftSecurityTestsLab,
  artifactSigningVerificationLab,
  ephemeralEnvironmentSecurityLab,
  dependencyCacheHardeningLab,
  releaseApprovalControlsLab,
  cloudWorkloadIdentityLab,
  incidentReadyPipelinesLab,
  apiAuthenticationPatternsLab,
  authorizationCheckOrderLab,
  rateLimitingStrategiesLab,
  jsonInputSanitizationLab,
  jwtValidationBasicsLab,
  refreshTokenRotationLab,
  oauthRedirectValidationLab,
  serviceToServiceAuthLab,
  graphqlResolverAuthorizationLab,
  webhookSignatureVerificationLab,
  idempotencyReplayDefenseLab,
  jobQueueHardeningLab,
  multiTenantDataIsolationLab,
  apiVersioningSecurityLab,
  backendAbuseObservabilityLab,
  secureStorageBasicsLab,
  certificatePinningDecisionsLab,
  mobileAuthTokenHandlingLab,
  reverseEngineeringRiskReviewLab,
  obfuscationSymbolStrippingLab,
  secureMobileNetworkingLab,
  localDataEncryptionLab,
  mobileLoggingRedactionLab,
  clipboardScreenshotHygieneLab,
  deepLinkValidationLab,
  rootedDeviceDetectionLab,
  clientSideSecretAvoidanceLab,
  biometricFallbackSecurityLab,
  thirdPartySdkReviewLab,
  mobileDataLeakagePreventionLab,
].sort((a, b) => a.sortOrder - b.sortOrder);
