// ============================================================
// DCI Secure Development Labs — Learning Paths
// Generated by scripts/generate-dci-programming-content.mjs
// ============================================================

export interface LearningPath {
  id: string;
  title: string;
  name: string;
  description: string;
  targetAudience: string;
  labIds: string[];
  icon: string;
}

export const learningPaths: LearningPath[] = [
  {
    "id": "secure-coding-fundamentals",
    "title": "Secure Coding Fundamentals",
    "name": "Secure Coding Fundamentals",
    "description": "Build foundational coding habits that prevent vulnerabilities before they ship to production.",
    "targetAudience": "Developers, junior engineers, and career switchers",
    "labIds": [
      "input-validation-basics",
      "canonicalization-normalization",
      "output-encoding-templates",
      "safe-dom-updates",
      "authentication-basics",
      "registration-rate-limits",
      "session-id-generation",
      "session-fixation-defense",
      "secure-error-handling",
      "secure-logging-basics",
      "dependency-boundary-checks",
      "least-privilege-defaults",
      "owasp-top10-mapping",
      "insecure-deserialization-basics",
      "path-traversal-defense",
      "command-injection-guardrails",
      "secrets-in-code-review",
      "memory-safe-string-handling",
      "secure-feature-rollouts",
      "threat-modeling-for-devs"
    ],
    "icon": "ShieldCheck"
  },
  {
    "id": "web-application-security",
    "title": "Web Application Security",
    "name": "Web Application Security",
    "description": "Protect modern web applications from common browser, session, and request-layer attacks.",
    "targetAudience": "Frontend, backend, and full-stack engineers",
    "labIds": [
      "reflected-xss-prevention",
      "stored-xss-comment-moderation",
      "dom-xss-client-rendering",
      "csrf-token-rotation",
      "same-site-cookie-policies",
      "sql-parameterized-queries",
      "orm-query-builder-safety",
      "content-security-policy-basics",
      "clickjacking-frame-ancestors",
      "secure-cookie-hardening",
      "file-upload-validation",
      "template-injection-defense",
      "open-redirect-controls",
      "ssrf-guardrails",
      "cors-origin-review",
      "websocket-session-security",
      "cache-poisoning-defense",
      "third-party-script-governance",
      "browser-storage-hygiene",
      "web-error-observability"
    ],
    "icon": "Globe"
  },
  {
    "id": "code-review-analysis",
    "title": "Code Review & Analysis",
    "name": "Code Review & Analysis",
    "description": "Learn how to spot risky changes, triage findings, and leave review feedback that leads to safer code.",
    "targetAudience": "Reviewers, staff engineers, and AppSec partners",
    "labIds": [
      "auth-bypass-pull-requests",
      "insecure-randomness-review",
      "taint-flow-review",
      "regex-dos-review",
      "static-analysis-basics",
      "dependency-scan-triage",
      "code-smell-risk-ranking",
      "unsafe-crypto-review",
      "access-control-diff-analysis",
      "logging-gap-review",
      "secrets-detection-prs",
      "review-comments-security",
      "secure-refactor-triage",
      "architecture-hotspots-analysis",
      "sast-rule-tuning-review"
    ],
    "icon": "Search"
  },
  {
    "id": "devsecops-practices",
    "title": "DevSecOps Practices",
    "name": "DevSecOps Practices",
    "description": "Secure the pipeline, the platform, and the release process that moves code into production.",
    "targetAudience": "Platform engineers, SREs, and DevSecOps teams",
    "labIds": [
      "ci-pipeline-least-privilege",
      "build-agent-secrets-management",
      "sbom-generation-review",
      "container-base-image-hardening",
      "dockerfile-security-checks",
      "kubernetes-manifest-security",
      "iac-scanning",
      "policy-as-code-guardrails",
      "shift-left-security-tests",
      "artifact-signing-verification",
      "ephemeral-environment-security",
      "dependency-cache-hardening",
      "release-approval-controls",
      "cloud-workload-identity",
      "incident-ready-pipelines"
    ],
    "icon": "Workflow"
  },
  {
    "id": "api-backend-security",
    "title": "API & Backend Security",
    "name": "API & Backend Security",
    "description": "Protect API consumers, backend services, and asynchronous workflows from abuse and data exposure.",
    "targetAudience": "Backend engineers and platform API teams",
    "labIds": [
      "api-authentication-patterns",
      "authorization-check-order",
      "rate-limiting-strategies",
      "json-input-sanitization",
      "jwt-validation-basics",
      "refresh-token-rotation",
      "oauth-redirect-validation",
      "service-to-service-auth",
      "graphql-resolver-authorization",
      "webhook-signature-verification",
      "idempotency-replay-defense",
      "job-queue-hardening",
      "multi-tenant-data-isolation",
      "api-versioning-security",
      "backend-abuse-observability"
    ],
    "icon": "Server"
  },
  {
    "id": "mobile-client-security",
    "title": "Mobile & Client Security",
    "name": "Mobile & Client Security",
    "description": "Protect client-side state, mobile networking, and distributed binaries from common abuse paths.",
    "targetAudience": "Mobile engineers and client platform teams",
    "labIds": [
      "secure-storage-basics",
      "certificate-pinning-decisions",
      "mobile-auth-token-handling",
      "reverse-engineering-risk-review",
      "obfuscation-symbol-stripping",
      "secure-mobile-networking",
      "local-data-encryption",
      "mobile-logging-redaction",
      "clipboard-screenshot-hygiene",
      "deep-link-validation",
      "rooted-device-detection",
      "client-side-secret-avoidance",
      "biometric-fallback-security",
      "third-party-sdk-review",
      "mobile-data-leakage-prevention"
    ],
    "icon": "Smartphone"
  }
];
