// ============================================================
// DCI Data Analytics Labs — Lab Catalog
// Generated by scripts/generate-dci-data-analytics-content.mjs
// ============================================================

import type { LabManifest } from "../types/manifest";
import { selectBasicsLab } from "./labs/select-basics";
import { whereFiltersLab } from "./labs/where-filters";
import { orderByLimitLab } from "./labs/order-by-limit";
import { calculatedColumnsLab } from "./labs/calculated-columns";
import { nullHandlingLab } from "./labs/null-handling";
import { caseExpressionsLab } from "./labs/case-expressions";
import { innerJoinsLab } from "./labs/inner-joins";
import { leftJoinsLab } from "./labs/left-joins";
import { multiTableJoinsLab } from "./labs/multi-table-joins";
import { groupByBasicsLab } from "./labs/group-by-basics";
import { havingFiltersLab } from "./labs/having-filters";
import { aggregateMetricsLab } from "./labs/aggregate-metrics";
import { dateFunctionsLab } from "./labs/date-functions";
import { stringCleanupLab } from "./labs/string-cleanup";
import { subqueriesLab } from "./labs/subqueries";
import { correlatedSubqueriesLab } from "./labs/correlated-subqueries";
import { cteBasicsLab } from "./labs/cte-basics";
import { recursiveCtesLab } from "./labs/recursive-ctes";
import { unionSetOpsLab } from "./labs/union-set-ops";
import { queryDebuggingLab } from "./labs/query-debugging";
import { normalizationBasicsLab } from "./labs/normalization-basics";
import { entityRelationshipMappingLab } from "./labs/entity-relationship-mapping";
import { primaryVsSurrogateKeysLab } from "./labs/primary-vs-surrogate-keys";
import { foreignKeyDesignLab } from "./labs/foreign-key-design";
import { uniqueConstraintsLab } from "./labs/unique-constraints";
import { checkConstraintsLab } from "./labs/check-constraints";
import { indexingStrategyLab } from "./labs/indexing-strategy";
import { compositeIndexesLab } from "./labs/composite-indexes";
import { partitionKeyPlanningLab } from "./labs/partition-key-planning";
import { schemaMigrationsLab } from "./labs/schema-migrations";
import { denormalizationTradeoffsLab } from "./labs/denormalization-tradeoffs";
import { auditColumnsLab } from "./labs/audit-columns";
import { cascadingRulesLab } from "./labs/cascading-rules";
import { materializedViewsLab } from "./labs/materialized-views";
import { schemaVersioningLab } from "./labs/schema-versioning";
import { cohortRetentionLab } from "./labs/cohort-retention";
import { rollingAveragesLab } from "./labs/rolling-averages";
import { percentileAnalysisLab } from "./labs/percentile-analysis";
import { medianWithWindowFunctionsLab } from "./labs/median-with-window-functions";
import { rankAndDenseRankLab } from "./labs/rank-and-dense-rank";
import { lagLeadAnomaliesLab } from "./labs/lag-lead-anomalies";
import { funnelAnalysisLab } from "./labs/funnel-analysis";
import { customerSegmentationLab } from "./labs/customer-segmentation";
import { basketAnalysisLab } from "./labs/basket-analysis";
import { revenueByRegionLab } from "./labs/revenue-by-region";
import { pivotCrossTabLab } from "./labs/pivot-cross-tab";
import { varianceToTargetLab } from "./labs/variance-to-target";
import { conversionRateAnalysisLab } from "./labs/conversion-rate-analysis";
import { seasonalityDetectionLab } from "./labs/seasonality-detection";
import { outlierScreeningLab } from "./labs/outlier-screening";
import { statisticalSamplingLab } from "./labs/statistical-sampling";
import { confidenceIntervalPrepLab } from "./labs/confidence-interval-prep";
import { abTestReadoutLab } from "./labs/ab-test-readout";
import { inventoryTurnoverAnalysisLab } from "./labs/inventory-turnover-analysis";
import { churnSignalAnalysisLab } from "./labs/churn-signal-analysis";
import { ingestionCheckpointsLab } from "./labs/ingestion-checkpoints";
import { deduplicationRulesLab } from "./labs/deduplication-rules";
import { schemaDriftTriageLab } from "./labs/schema-drift-triage";
import { nullImputationPolicyLab } from "./labs/null-imputation-policy";
import { typeCastingFailuresLab } from "./labs/type-casting-failures";
import { lateArrivingDataLab } from "./labs/late-arriving-data";
import { incrementalLoadsLab } from "./labs/incremental-loads";
import { fullRefreshVsIncrementalLab } from "./labs/full-refresh-vs-incremental";
import { surrogateKeyGenerationLab } from "./labs/surrogate-key-generation";
import { dataQualityThresholdsLab } from "./labs/data-quality-thresholds";
import { reconciliationQueriesLab } from "./labs/reconciliation-queries";
import { orchestrationDependenciesLab } from "./labs/orchestration-dependencies";
import { backfillPlanningLab } from "./labs/backfill-planning";
import { pipelineSlaMonitoringLab } from "./labs/pipeline-sla-monitoring";
import { transformationLineageLab } from "./labs/transformation-lineage";
import { executiveKpiScorecardLab } from "./labs/executive-kpi-scorecard";
import { dashboardFilterDesignLab } from "./labs/dashboard-filter-design";
import { metricLayerGovernanceLab } from "./labs/metric-layer-governance";
import { reportingGrainAlignmentLab } from "./labs/reporting-grain-alignment";
import { selfServiceDatasetCurationLab } from "./labs/self-service-dataset-curation";
import { fiscalCalendarReportingLab } from "./labs/fiscal-calendar-reporting";
import { salesPipelineForecastingLab } from "./labs/sales-pipeline-forecasting";
import { customerSupportDashboardLab } from "./labs/customer-support-dashboard";
import { marketingAttributionReportingLab } from "./labs/marketing-attribution-reporting";
import { financeCloseReportingLab } from "./labs/finance-close-reporting";
import { inventoryDashboardStorytellingLab } from "./labs/inventory-dashboard-storytelling";
import { stakeholderMetricDefinitionsLab } from "./labs/stakeholder-metric-definitions";
import { drillDownPathsLab } from "./labs/drill-down-paths";
import { alertThresholdReportingLab } from "./labs/alert-threshold-reporting";
import { narrativeInsightsLab } from "./labs/narrative-insights";
import { queryPlanOptimizationLab } from "./labs/query-plan-optimization";
import { joinOrderTuningLab } from "./labs/join-order-tuning";
import { partitionPruningLab } from "./labs/partition-pruning";
import { clusteringStrategyLab } from "./labs/clustering-strategy";
import { materializationVsComputeLab } from "./labs/materialization-vs-compute";
import { storedProcedureReviewLab } from "./labs/stored-procedure-review";
import { transactionIsolationChoicesLab } from "./labs/transaction-isolation-choices";
import { lockContentionTriageLab } from "./labs/lock-contention-triage";
import { tempTableOptimizationLab } from "./labs/temp-table-optimization";
import { workloadManagementLab } from "./labs/workload-management";
import { costBasedOptimizationLab } from "./labs/cost-based-optimization";
import { indexMaintenanceAutomationLab } from "./labs/index-maintenance-automation";
import { parameterSniffingAnalysisLab } from "./labs/parameter-sniffing-analysis";
import { warehouseScalingDecisionsLab } from "./labs/warehouse-scaling-decisions";
import { cacheInvalidationAnalyticsLab } from "./labs/cache-invalidation-analytics";

export const labCatalog: LabManifest[] = [
  selectBasicsLab,
  whereFiltersLab,
  orderByLimitLab,
  calculatedColumnsLab,
  nullHandlingLab,
  caseExpressionsLab,
  innerJoinsLab,
  leftJoinsLab,
  multiTableJoinsLab,
  groupByBasicsLab,
  havingFiltersLab,
  aggregateMetricsLab,
  dateFunctionsLab,
  stringCleanupLab,
  subqueriesLab,
  correlatedSubqueriesLab,
  cteBasicsLab,
  recursiveCtesLab,
  unionSetOpsLab,
  queryDebuggingLab,
  normalizationBasicsLab,
  entityRelationshipMappingLab,
  primaryVsSurrogateKeysLab,
  foreignKeyDesignLab,
  uniqueConstraintsLab,
  checkConstraintsLab,
  indexingStrategyLab,
  compositeIndexesLab,
  partitionKeyPlanningLab,
  schemaMigrationsLab,
  denormalizationTradeoffsLab,
  auditColumnsLab,
  cascadingRulesLab,
  materializedViewsLab,
  schemaVersioningLab,
  cohortRetentionLab,
  rollingAveragesLab,
  percentileAnalysisLab,
  medianWithWindowFunctionsLab,
  rankAndDenseRankLab,
  lagLeadAnomaliesLab,
  funnelAnalysisLab,
  customerSegmentationLab,
  basketAnalysisLab,
  revenueByRegionLab,
  pivotCrossTabLab,
  varianceToTargetLab,
  conversionRateAnalysisLab,
  seasonalityDetectionLab,
  outlierScreeningLab,
  statisticalSamplingLab,
  confidenceIntervalPrepLab,
  abTestReadoutLab,
  inventoryTurnoverAnalysisLab,
  churnSignalAnalysisLab,
  ingestionCheckpointsLab,
  deduplicationRulesLab,
  schemaDriftTriageLab,
  nullImputationPolicyLab,
  typeCastingFailuresLab,
  lateArrivingDataLab,
  incrementalLoadsLab,
  fullRefreshVsIncrementalLab,
  surrogateKeyGenerationLab,
  dataQualityThresholdsLab,
  reconciliationQueriesLab,
  orchestrationDependenciesLab,
  backfillPlanningLab,
  pipelineSlaMonitoringLab,
  transformationLineageLab,
  executiveKpiScorecardLab,
  dashboardFilterDesignLab,
  metricLayerGovernanceLab,
  reportingGrainAlignmentLab,
  selfServiceDatasetCurationLab,
  fiscalCalendarReportingLab,
  salesPipelineForecastingLab,
  customerSupportDashboardLab,
  marketingAttributionReportingLab,
  financeCloseReportingLab,
  inventoryDashboardStorytellingLab,
  stakeholderMetricDefinitionsLab,
  drillDownPathsLab,
  alertThresholdReportingLab,
  narrativeInsightsLab,
  queryPlanOptimizationLab,
  joinOrderTuningLab,
  partitionPruningLab,
  clusteringStrategyLab,
  materializationVsComputeLab,
  storedProcedureReviewLab,
  transactionIsolationChoicesLab,
  lockContentionTriageLab,
  tempTableOptimizationLab,
  workloadManagementLab,
  costBasedOptimizationLab,
  indexMaintenanceAutomationLab,
  parameterSniffingAnalysisLab,
  warehouseScalingDecisionsLab,
  cacheInvalidationAnalyticsLab,
].sort((a, b) => a.sortOrder - b.sortOrder);
