// ============================================================
// DCI Data Analytics Labs — Learning Paths
// Generated by scripts/generate-dci-data-analytics-content.mjs
// ============================================================

export interface LearningPath {
  id: string;
  title: string;
  name: string;
  description: string;
  targetAudience: string;
  labIds: string[];
  icon: string;
}

export const learningPaths: LearningPath[] = [
  {
    "id": "sql-fundamentals",
    "title": "SQL Fundamentals",
    "name": "SQL Fundamentals",
    "description": "Master the core SQL building blocks that make analytics work: SELECT, WHERE, JOIN, GROUP BY, subqueries, and CTEs.",
    "targetAudience": "Aspiring analysts, career switchers, and SQL beginners",
    "labIds": [
      "select-basics",
      "where-filters",
      "order-by-limit",
      "calculated-columns",
      "null-handling",
      "case-expressions",
      "inner-joins",
      "left-joins",
      "multi-table-joins",
      "group-by-basics",
      "having-filters",
      "aggregate-metrics",
      "date-functions",
      "string-cleanup",
      "subqueries",
      "correlated-subqueries",
      "cte-basics",
      "recursive-ctes",
      "union-set-ops",
      "query-debugging"
    ],
    "icon": "Database"
  },
  {
    "id": "database-design",
    "title": "Database Design",
    "name": "Database Design",
    "description": "Learn how sound schemas are built: normalization, ERDs, indexing, constraints, and safe migration habits.",
    "targetAudience": "Analytics engineers, backend developers, and data modelers",
    "labIds": [
      "normalization-basics",
      "entity-relationship-mapping",
      "primary-vs-surrogate-keys",
      "foreign-key-design",
      "unique-constraints",
      "check-constraints",
      "indexing-strategy",
      "composite-indexes",
      "partition-key-planning",
      "schema-migrations",
      "denormalization-tradeoffs",
      "audit-columns",
      "cascading-rules",
      "materialized-views",
      "schema-versioning"
    ],
    "icon": "GitBranch"
  },
  {
    "id": "data-analysis",
    "title": "Data Analysis",
    "name": "Data Analysis",
    "description": "Practice the SQL patterns analysts use every day: aggregations, window functions, pivots, and statistical readouts.",
    "targetAudience": "Product analysts, business analysts, and growth teams",
    "labIds": [
      "cohort-retention",
      "rolling-averages",
      "percentile-analysis",
      "median-with-window-functions",
      "rank-and-dense-rank",
      "lag-lead-anomalies",
      "funnel-analysis",
      "customer-segmentation",
      "basket-analysis",
      "revenue-by-region",
      "pivot-cross-tab",
      "variance-to-target",
      "conversion-rate-analysis",
      "seasonality-detection",
      "outlier-screening",
      "statistical-sampling",
      "confidence-interval-prep",
      "ab-test-readout",
      "inventory-turnover-analysis",
      "churn-signal-analysis"
    ],
    "icon": "BarChart3"
  },
  {
    "id": "data-pipelines",
    "title": "Data Pipelines",
    "name": "Data Pipelines",
    "description": "Build instincts for ETL reliability: cleaning, transformation, scheduling, schema drift, and quality checks.",
    "targetAudience": "Analytics engineers, data engineers, and data operations teams",
    "labIds": [
      "ingestion-checkpoints",
      "deduplication-rules",
      "schema-drift-triage",
      "null-imputation-policy",
      "type-casting-failures",
      "late-arriving-data",
      "incremental-loads",
      "full-refresh-vs-incremental",
      "surrogate-key-generation",
      "data-quality-thresholds",
      "reconciliation-queries",
      "orchestration-dependencies",
      "backfill-planning",
      "pipeline-sla-monitoring",
      "transformation-lineage"
    ],
    "icon": "Workflow"
  },
  {
    "id": "business-intelligence",
    "title": "Business Intelligence",
    "name": "Business Intelligence",
    "description": "Design dashboards and reporting logic that keep KPIs clear, trustworthy, and easy to act on.",
    "targetAudience": "BI developers, reporting analysts, and operations leaders",
    "labIds": [
      "executive-kpi-scorecard",
      "dashboard-filter-design",
      "metric-layer-governance",
      "reporting-grain-alignment",
      "self-service-dataset-curation",
      "fiscal-calendar-reporting",
      "sales-pipeline-forecasting",
      "customer-support-dashboard",
      "marketing-attribution-reporting",
      "finance-close-reporting",
      "inventory-dashboard-storytelling",
      "stakeholder-metric-definitions",
      "drill-down-paths",
      "alert-threshold-reporting",
      "narrative-insights"
    ],
    "icon": "Presentation"
  },
  {
    "id": "advanced-analytics",
    "title": "Advanced Analytics",
    "name": "Advanced Analytics",
    "description": "Tackle the hard stuff: optimization, partitioning, stored procedures, workload management, and performance tuning.",
    "targetAudience": "Senior analysts, analytics engineers, and warehouse specialists",
    "labIds": [
      "query-plan-optimization",
      "join-order-tuning",
      "partition-pruning",
      "clustering-strategy",
      "materialization-vs-compute",
      "stored-procedure-review",
      "transaction-isolation-choices",
      "lock-contention-triage",
      "temp-table-optimization",
      "workload-management",
      "cost-based-optimization",
      "index-maintenance-automation",
      "parameter-sniffing-analysis",
      "warehouse-scaling-decisions",
      "cache-invalidation-analytics"
    ],
    "icon": "Gauge"
  }
];
