import type { LabManifest } from "../../types/manifest";

export const cachingStrategyLab: LabManifest = {
  schemaVersion: "1.1",
  id: "caching-strategy",
  version: 1,
  title: "Caching Strategy Design",
  tier: "intermediate",
  track: "cloud-architecture",
  difficulty: "moderate",
  accessLevel: "free",
  tags: ["caching", "redis", "cdn", "cache-invalidation", "performance"],
  description:
    "Design effective caching strategies by selecting the right cache tier, eviction policy, invalidation approach, and consistency model for different data types and access patterns.",
  estimatedMinutes: 20,
  learningObjectives: [
    "Select the appropriate caching tier (CDN, application, database) for a given data type",
    "Apply correct cache invalidation strategies for mutable versus immutable data",
    "Choose between cache-aside, write-through, and write-behind patterns",
    "Identify when a cache makes a consistency problem worse rather than better",
  ],
  sortOrder: 407,
  status: "published",
  prerequisites: [],
  rendererType: "action-rationale",
  scenarios: [
    {
      type: "action-rationale",
      id: "cache-product-data",
      title: "Caching Strategy for Product Catalog Pages",
      context:
        "Your e-commerce product detail pages are generated by assembling product data, pricing, and inventory from three backend services. Average page assembly time is 320ms. The site handles 4,000 requests/second at peak. Product data changes infrequently (average 2 updates per product per day) but prices can change every 15 minutes for flash sales.",
      displayFields: [
        { label: "Page Assembly Time", value: "320ms average", emphasis: "warn" },
        { label: "Peak Traffic", value: "4,000 req/s", emphasis: "warn" },
        { label: "Product Data Update Freq.", value: "~2/day per product", emphasis: "normal" },
        { label: "Price Update Freq.", value: "Every 15 min (flash sales)", emphasis: "critical" },
      ],
      actions: [
        { id: "tiered-cache", label: "Cache assembled product HTML at the CDN for 15 minutes; cache raw product/price data in application cache with separate TTLs", color: "green" },
        { id: "full-page-24h", label: "Cache full assembled pages in CDN for 24 hours; purge manually on product updates", color: "yellow" },
        { id: "no-cache-price", label: "Cache everything except pricing — fetch price live on every request to ensure accuracy", color: "orange" },
        { id: "db-query-cache", label: "Enable database query result caching for all three backend services", color: "blue" },
      ],
      correctActionId: "tiered-cache",
      rationales: [
        { id: "r-tiered", text: "A tiered approach solves both constraints: CDN caches assembled pages for 15 minutes matching the price update cadence, while the application cache holds raw product/price data with independent TTLs — product data at hours, price data at 15 minutes. This reduces origin load by 95%+ while keeping prices within the SLA window." },
        { id: "r-24h-cdn", text: "A 24-hour CDN TTL works for static product data but price changes during flash sales would serve stale prices for up to 24 hours. Manual purging is error-prone and slow under flash sale conditions with thousands of SKUs changing simultaneously." },
        { id: "r-no-cache-price", text: "Fetching price live on every request for 4,000 req/s means 4,000 pricing service calls per second, which re-introduces the latency and load problem the cache was meant to solve. Separating price TTL is the better approach." },
        { id: "r-db-query", text: "Database query caching reduces database load but does not address the page assembly latency (320ms) or the CDN-level caching that would reduce the number of requests reaching the application tier at all." },
      ],
      correctRationaleId: "r-tiered",
      feedback: {
        perfect: "Correct. Tiered caching with separate TTLs for different data types is the production-grade approach for content with mixed update frequencies.",
        partial: "Your approach reduces some load but either over-caches dynamic price data or under-caches static product data. Separate TTLs per data type is the key insight.",
        wrong: "Consider that product descriptions and prices update at very different rates. A single cache policy for both creates either staleness or excessive cache misses.",
      },
    },
    {
      type: "action-rationale",
      id: "cache-session-write",
      title: "Write Strategy for Session Data Cache",
      context:
        "Your user session service stores session tokens in a distributed cache (Redis). Sessions are created on login and updated on every API call (last-seen timestamp, permissions refresh). The session data must be queryable for security audits. A cache node failure cannot silently lose sessions — logged-in users cannot be forced back to the login page unexpectedly.",
      displayFields: [
        { label: "Session Update Freq.", value: "Every API call (~every 2 seconds per user)", emphasis: "warn" },
        { label: "Durability Requirement", value: "No silent loss on node failure", emphasis: "critical" },
        { label: "Audit Access", value: "Sessions queryable by security team", emphasis: "normal" },
        { label: "Active Sessions", value: "~80,000 concurrent", emphasis: "normal" },
      ],
      actions: [
        { id: "write-through", label: "Write-through: write to cache and database synchronously on every session update", color: "green" },
        { id: "cache-only", label: "Cache-only: store sessions only in Redis, rely on Redis persistence for durability", color: "yellow" },
        { id: "write-behind", label: "Write-behind: write to cache immediately, batch-flush to database every 30 seconds", color: "blue" },
        { id: "cache-aside-lazy", label: "Cache-aside: write directly to database, populate cache lazily on first read after miss", color: "orange" },
      ],
      correctActionId: "write-through",
      rationales: [
        { id: "r-write-through", text: "Write-through ensures the database always has a current copy of session state. On cache failure, sessions can be rehydrated from the database, satisfying the no-silent-loss requirement. The audit access requirement is also met since the database is always current." },
        { id: "r-cache-only", text: "Redis persistence (RDB/AOF) reduces but does not eliminate data loss risk. A node failure before a persistence checkpoint can still lose sessions. This does not meet the 'no silent loss' durability requirement." },
        { id: "r-write-behind", text: "Write-behind improves write performance but creates a 30-second window where the cache and database are out of sync. Sessions updated in that window are lost on cache failure, violating the durability requirement." },
        { id: "r-cache-aside-lazy", text: "Cache-aside with lazy population is excellent for read-heavy, infrequently-updated data. For session data updated on every API call, every write bypasses the cache and the database becomes the hot write target, eliminating the cache performance benefit." },
      ],
      correctRationaleId: "r-write-through",
      feedback: {
        perfect: "Correct. Write-through guarantees the database is always current, enabling session recovery from the database on cache failure without user impact.",
        partial: "Your write strategy has some durability properties but creates a gap window where session updates could be lost on cache failure.",
        wrong: "The key constraint is 'no silent loss on node failure.' This eliminates cache-only and asynchronous write strategies. Consider which pattern keeps the database synchronized in real time.",
      },
    },
    {
      type: "action-rationale",
      id: "cache-invalidation",
      title: "Cache Invalidation for User Profile Data",
      context:
        "User profile data (name, avatar, preferences) is cached in an application-tier Redis instance with a 1-hour TTL. A user updates their display name. For the next hour, other users may see their old name in comments and messages until the cache expires. The product team wants near-real-time consistency after profile updates.",
      displayFields: [
        { label: "Current TTL", value: "1 hour", emphasis: "warn" },
        { label: "Update Frequency", value: "~0.1% of users update profile daily", emphasis: "normal" },
        { label: "Staleness Observed", value: "Up to 1 hour after user update", emphasis: "critical" },
        { label: "Read Frequency", value: "Profile data read 200x/day per active user", emphasis: "warn" },
      ],
      actions: [
        { id: "event-invalidation", label: "Publish a ProfileUpdated event on profile save; cache consumers subscribe and delete affected cache keys", color: "green" },
        { id: "reduce-ttl", label: "Reduce TTL from 1 hour to 30 seconds to minimize staleness window", color: "yellow" },
        { id: "version-key", label: "Include a profile version number in the cache key; increment version on update to auto-invalidate", color: "blue" },
        { id: "no-cache", label: "Remove the cache entirely and fetch profile data directly from the database on every read", color: "red" },
      ],
      correctActionId: "event-invalidation",
      rationales: [
        { id: "r-event", text: "Event-driven invalidation removes the specific cache key immediately on update, achieving near-real-time consistency for the small fraction of users who update their profile while maintaining high cache hit rates for the 99.9% who do not update." },
        { id: "r-short-ttl", text: "Reducing TTL to 30 seconds still allows a 30-second staleness window (which may not meet 'near real-time') and causes 120x more cache misses per user per day, increasing database load by over 100x. This defeats the cache's purpose." },
        { id: "r-version-key", text: "Version-based cache keys solve the staleness problem but leave orphaned old-version keys in the cache consuming memory until they expire. Cache size grows unbounded without a separate cleanup mechanism." },
        { id: "r-no-cache", text: "Removing the cache eliminates the staleness problem but restores the original database load. At 200 profile reads per user per day across millions of users, the database cannot handle this read volume without the cache." },
      ],
      correctRationaleId: "r-event",
      feedback: {
        perfect: "Correct. Event-driven invalidation is the production standard for mutable entity caching — it achieves immediate consistency for updates while preserving high hit rates for unchanged data.",
        partial: "Your approach reduces staleness but either degrades cache hit rate significantly or creates cache memory management issues.",
        wrong: "Reducing TTL is a blunt instrument that sacrifices hit rate for freshness. Consider how you can achieve both: instant invalidation for changed data and indefinite caching for unchanged data.",
      },
    },
  ],
  hints: [
    "Data with different update frequencies should have different cache TTLs — don't use one TTL for mixed data types in the same cache entry.",
    "Write-through is the correct cache write strategy when durability is required and you cannot afford silent data loss on cache failure.",
    "Event-driven cache invalidation achieves near-real-time consistency for updated entities without sacrificing hit rate on unchanged entities.",
  ],
  scoring: {
    maxScore: 100,
    hintPenalty: 5,
    penalties: { perfect: 0, partial: 10, wrong: 20 },
    passingThresholds: { pass: 80, partial: 50 },
  },
  careerInsight:
    "Phil Karlton's famous quip — 'There are only two hard things in computer science: cache invalidation and naming things' — understates how costly cache correctness mistakes are in production. Architects who design cache invalidation strategies proactively (rather than discovering staleness bugs post-launch) save significant engineering time and customer trust.",
  toolRelevance: [
    "Redis",
    "Memcached",
    "Amazon ElastiCache",
    "Azure Cache for Redis",
    "Cloudflare Cache",
  ],
  createdAt: "2026-03-28",
  updatedAt: "2026-03-28",
};
